version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploytest1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ooa5zi7so6ul"
s3_prefix = "deploytest1"
region = "us-west-2"
profile = "t2-west2-dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "s3BucketName=\"bk21\" DatabaseUser=\"t2admin\""
