version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploy2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1fiyjcrcf60cy"
s3_prefix = "deploy2"
region = "us-west-2"
profile = "sathcftest"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "s3BucketName=\"bk16\" DatabaseUser=\"t2admin\""
