version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sambk13"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19aocmplssj0w"
s3_prefix = "sambk13"
region = "us-east-1"
profile = "t2-east1-dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "s3BucketName=\"bk13\" DatabaseUser=\"t2admin\""
